In [1]:
import os
import torch, torchvision

os.chdir("/home/kishen/documents/python_projects/stanford_dogs/")
from src.data import ImageDataset

In [2]:
#read in image data
path = "/home/kishen/documents/python_projects/stanford_dogs/data/Images"

transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Resize((224, 224)),
    torchvision.transforms.RandomHorizontalFlip(p=.55)

])

dataset = ImageDataset(root_directory=path, transform=transform)

In [3]:
#split data
train_size, val_size = int(dataset.__len__() * .8) , int(dataset.__len__() * .2)

ran_gen= torch.Generator().manual_seed(24)

train_data, val_data = torch.utils.data.random_split(dataset, 
                                                    [train_size, val_size],
                                                     generator= ran_gen)




In [5]:
#calculcate train data stats
from src.modeling import calculate_channel_means, calculate_channel_sds

display(calculate_channel_means(train_data, 'image'))
#tensor([0.4760, 0.4517, 0.3907])

display(calculate_channel_sds(train_data, 'image'))
#tensor([0.2362, 0.2314, 0.2307])

#normalize data

/home/kishen/.virtualenvs/stanford_dogs/lib/python3.11/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(


tensor([0.4760, 0.4517, 0.3907])

tensor([0.2362, 0.2314, 0.2307])